sudo: required
language: go
services:
- docker
go:
- 1.11
go_import_path: citest
before_install:
- openssl aes-256-cbc -K $encrypted_b8a7b184d8e7_key -iv $encrypted_b8a7b184d8e7_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod +x release
- chmod +x build
- chmod 600 ~/.ssh/id_rsa
addons:
    ssh_known_hosts: 139.198.12.99
install:
- "./release"
script:
- docker build --rm -t mybumbelbee/citest .
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  docker push mybumbelbee/citest; else echo $TRAVIS_BRANCH; docker tag mybumbelbee/citest
  mybumbelbee/citest:$TRAVIS_BRANCH; docker push mybumbelbee/citest:$TRAVIS_BRANCH;
  fi
- ssh root@139.198.12.99 -p 16022 docker run -d -p 8001 mybumbelbee/citest
