FROM golang:1.11-alpine

ENV GOPATH /go
RUN apk --update add bash git curl

RUN mkdir -p "$GOPATH/src/" "$GOPATH/bin" && chmod -R 777 "$GOPATH" && \
    mkdir -p /go/src/citest && \
    ln -s /go/src/citest /app

WORKDIR /app